version: '3.8'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
        container_name: elasticsearch
        environment: 
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - 9200:9200
            - 9300:9300
        volumes: 
            - ./es/data/:/usr/share/elasticsearch/data/
            - ./es/logs/:/usr/share/elasticsearch/logs/    

    kibana:
        image: docker.elastic.co/kibana/kibana:6.8.10
        container_name: kibana
        links: 
            - elasticsearch:elasticsearch
        ports: 
            - 5601:5601  
        depends_on: 
            - elasticsearch    
    
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: canal
            MYSQL_PASSWORD: canal
        volumes:
            - ./mysql/data/:/var/lib/mysql/
            - ./mysql/mysql.conf.d/:/etc/mysql/mysql.conf.d/
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports: 
            - 3306:3306

    canal_server:
        image: canal/canal-server:v1.1.3
        container_name: canal_server
        environment: 
            - canal.instance.master.address=mysql:3306
            - canal.instance.mysql.slaveId=123
            - canal.destinations=example
            - canal.instance.dbUsername=canal
            - canal.instance.dbPassword=canal
            - canal.instance.connectionCharset=UTF-8
            - canal.instance.tsdb.enable=false
            - canal.instance.gtidon=false
            - canal.instance.filter.regex=.*\\..*
        links:
            - mysql:mysql
        ports: 
            - 11110:11110
            - 11111:11111
            - 11112:11112
            - 9100:9100
