version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:6.8.10
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es/shell:/es/shell
      - ./es/data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:6.8.10
    container_name: kibana
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: canal
      MYSQL_PASSWORD: canal
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./canal/:/canal
    ports:
      - 3306:3306
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch